# Generated by Django 2.1.4 on 2019-04-29 13:26

from django.db import migrations, models
import num.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SomeClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', num.models.CustomField()),
            ],
        ),
    ]
